# Generated by Django 5.1.1 on 2024-10-12 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_id', models.IntegerField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_applied', models.DateTimeField()),
                ('time_ended', models.DateTimeField()),
                ('connection_code', models.CharField(max_length=64)),
                ('average_work_time', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'appeals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppealIssues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'appeal_issues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=300)),
                ('image', models.CharField(default='http://127.0.0.1:9000/images/default.jpg', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'issues',
                'managed': False,
            },
        ),
    ]
